puts "The students of recent cohort at Makers Academy"
puts "---------------------"
puts "Andrew Johnson"
puts "Kevin Dorking"
puts "John Ford"
puts "sam Cox"
puts "Mark Spencer"
puts "Alfred Tarski"
